FyCas/Customer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, views_ajax

app_name = "customer"
urlpatterns = [
      path("", views.Dashboard.as_view(), name='dashboard'),
      path('add-customer/<int:pk>', views.AddCustomer.as_view(), name='add-customer'),
      path('detail-customer/<int:pk>', views.DetailCustomer.as_view(), name='detail-customer'),
      path('update-customer/<int:pk>', views.UpdateCustomer.as_view(), name='update-customer'),
      
      path('delete-customer/<int:pk>', views.DeleteCustomer.as_view(), name='delete-customer'),

      path('list-customer', views.ListCustomer.as_view(), name='list-customer'),
      path('card-customer/<int:pk>/<int:credit_id>', views.CardCustomer.as_view(), name='card-customer'),
      path('notary-customer/<int:pk>/<int:notary_id>', views.NotaryCustomer.as_view(), name='notary-customer'),
      
      path('create-credit/<int:pk>', views.CreateCredit.as_view(), name='create-credit'),
      path('update-credit/<int:pk>', views.UpdateCredit.as_view(), name='update-credit'),
      path('list-credit/<int:pk>', views.ListCredit.as_view(), name='list-credit'),

      path('create-credit-new/<int:pk>', views.CreateCreditNew.as_view(), name='create-credit-new'),

      path('calendario/', views.Calendario.as_view(), name='calendario'),

      path('configuraciones/', views.Configuraciones.as_view(), name='configuraciones'),

      path("detail-credit/customer/<int:pk>", views.DetailCreditCustomer.as_view(), name="detail-credit-cutomer"),

      path("no-approved/customer", views.NoApproved.as_view(), name='no-approved'),
      path("approved/customer/<int:pk>", views.Approved.as_view(), name='approved'),
      
      path("create/customer-debit", views.CreateCustomerDebit.as_view(), name='create-customer-debit'),
      path("mensaje/customer-debit", views.MensajeCustomerDebit.as_view(), name='mensaje-customer-debit'),

      path("select/customer", views.ListCustomerSelect.as_view(), name='select-customer'),
      
      path("customer-profile", views.CustomerProfile.as_view(), name='customer-profile'),
      path('mensajeria', views.Mensensajeria.as_view(), name='mensajeria'),

      path("prestamos", views.Prestamos.as_view(), name='prestamos'),
      
      path('ubicaciones', views.Ubicaciones.as_view(), name='ubicaciones'),
      path('agregar/<int:pk>', views.Agregar.as_view(), name='agregar'),

      path('listado-credit-redirect/<int:pk>', views.ListadoCredit_rederict.as_view(), name='listado-credit-redirect'),

      path('empresa', views.Empresa.as_view(), name='empresa'),
      path('calculadora', views.Calculadora.as_view(), name='calculadora'),

      # New Version
      path('crear-credito/<int:pk>', views.CrearCredito.as_view(), name='crear-credito'),
      path('list-all-credits', views.ListAllCredits.as_view(), name='list-all-credits'),

      path('search-company', views.SearchCompany.as_view(), name='search-company'),

      path('select-form', views.SelecForm.as_view(), name='select-form'),


      # Views Ajax``
      path('aplicar-pago', views_ajax.AplicarPago, name='aplicar-pago'),
      path("searching/customer", views_ajax.SearchCustomer, name="searching-customer"),
      path("verify/customer/", views_ajax.CustomerVerify, name="verify-true-customer"),
      path("verify-no/customer/", views_ajax.CustomerNoVerify, name="verify-false-customer"),
      path('calcular-mora', views_ajax.CalcularMora, name='calcular-mora'),
      path("turn-debit/customer/", views_ajax.TurnDebeit, name="turn-debit-customer"),
      path("turn-debit-follow/customer/", views_ajax.TurnDebeitFollow, name="turn-debit-customer-follow"),
      path("turn-debit-active/customer/", views_ajax.TurnDebeitActive, name="turn-debit-customer-active"),
      path("msg/customer/debit", views_ajax.MensajeCustomerDebit, name="msg-debit-customer"),
      path("create-credit-ajax/customer/", views_ajax.CreateCreditAjax, name="create-credit-ajax"),
      path("disable-customer/", views_ajax.DisableCustomer, name="disable-customer-ajax"),
      path("delete-credit", views_ajax.DeleteCreditAjax, name="delete-credit"),
      path('upload-image-url', views_ajax.UploadImageURL, name='upload-image-url'),
      

      path('chatgpt', views_ajax.ChatGPT, name='chatgpt'),

      path('aplicar-pago-cuota', views_ajax.AplicarPagoCuota, name='aplicar-pago-cuota'),

      path('abonar-capital', views_ajax.AbonarCapital, name='abonar-capital')
      
]

FyCas/FyCas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Customer.urls')),
    path('', include('Maps.urls')),
    path('', include('MensApp.urls')),
     path('', include('Shop.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FyCas/Maps/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "maps"
urlpatterns = [
      path('maps/customer', views.Maps.as_view(), name='maps-customer'),
      path('data-credito/', views.DataCredit.as_view(), name='data-credi')
      
]

FyCas/Customer/models.py
from django.db import models
from django.utils import timezone
from PIL import Image
import os
from django.core.files.base import ContentFile
from io import BytesIO

from django.contrib.auth.models import User




# Create your models here.

class Customer(models.Model):
    company= models.ForeignKey('Company', on_delete=models.CASCADE,  blank=True, null=True, related_name="company_customer")
    # Para el tema de las solicitudes, cuando el user ingresa por primera vez el estado permanece false durante los proximos 7 dias, sera descartado y eliminado de la base de datos ya que su aprobacion no fue verificada por lo tanto no cambio a " True " pero se guardada su DNI en una base de datos adicional mas adelante p
    not_aprobado = models.BooleanField(default=False,  blank=True)
    # Si 
    customer_verify = models.BooleanField(default=False,  blank=True)
   
    debit = models.BooleanField(default=False,  blank=True)
    
    debit_visit = models.BooleanField(default=False,  blank=True)
    debit_follow = models.BooleanField(default=False,  blank=True)

    
    # Datos Opcionales
    vehiculo = models.BooleanField(default=False,  blank=True)
    casa = models.BooleanField(default=False,  blank=True)
    tierra = models.BooleanField(default=False,  blank=True)
    
    hijos = models.BooleanField(default=False,  blank=True)
    saldar_deudas = models.BooleanField(default=False,  blank=True)

    
    # Preguntas 
    familiar_en_fycas = models.BooleanField(default=False, blank=True)
    fue_recomendado = models.BooleanField(default=False,  blank=True)
    
    monto_requerido = models.CharField(max_length=255, default='',  blank=True)
    fines = models.CharField(max_length=255, default='',  blank=True)
    

    is_active = models.BooleanField(default=True)
    name = models.CharField( max_length=255, )#Nombre
    last_name = models.CharField( max_length=255)#Apellido
    number = models.CharField( max_length=20, )#Numero local o Movile
    address = models.CharField( max_length=255, blank=True)#Direccion de donde recide
    email = models.EmailField(null=True, blank=True)#Correo electronico
    amount_purpose = models.TextField(blank=True, max_length=355)#Proposito por el que se solicita el prestamo
    work_information = models.TextField(blank=True, max_length=300)#Informacion donde trabaja
    references_peopple = models.TextField(blank=True, max_length=500)#Personas referentes
    dni = models.CharField( max_length=100) #Numero de Identidad
    amount = models.IntegerField(null=True)#Monto 
    no_account = models.IntegerField(default=0) #Numero de Cuentaloooo
    
    img1 = models.ImageField(upload_to="media/",  blank=True, null=True, default=None)
      #Foto de Cedula delantera
    img2 = models.ImageField(upload_to="media/", blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        # Save the original instance first to ensure img1 is available
        super(Customer, self).save(*args, **kwargs)

        if self.img1:
            try:
                img2 = self.img1.path
                # Open the original image
                img1_path = self.img1.path
                img1 = Image.open(img1_path)

                # Resize img1 to 250p resolution
                img1.thumbnail((50, 50))
                img1_io = BytesIO()
                img1.save(img1_io, format=img1.format, quality=50)  # Reduce quality to reduce file size

                self.img1.save(os.path.basename(self.img1.name), ContentFile(img1_io.getvalue()), save=False)
            except FileNotFoundError:
                pass

        super(Customer, self).save(*args, **kwargs)


    #Foto de Cedula tracera
    name_r1 = models.CharField( max_length=255,  )#Nombre
    name_r2 = models.CharField( max_length=255,  )#Nombre
    number_r1 = models.CharField(default="",  max_length=30)#Numero local o Movile
    number_r2 = models.CharField(default="",  max_length=30  )#Numero local o Movile
    
    # CaptureLocation
    lat = models.CharField(blank=True, max_length=100000000050005, default='')
    lon = models.CharField(blank=True, max_length=100000000000000055, default='')
    
    # Tipo de Entrada
    type_input = models.CharField(blank=True, max_length=2, default='P')
    #Sexo
    sexo = models.CharField(blank=True, max_length=2, default='M')
    # Estado Civil 
    estado_civil = models.CharField(blank=True, max_length=2, default='')
    # Ocupacion 
    ocupacion = models.CharField(blank=True, max_length=25, default='Estudiante')
    # Codigo de cliente
    code_customer = models.CharField(blank=True, max_length=122000, default='')
    # Date 
    nacimiento = models.CharField(blank=True, max_length=40, default='10/11/2001')
    # Nacionalidad 
    nacionalidad = models.CharField(blank=True, max_length=25, default='DOMINICANA')
    # Direccion
    direccion = models.CharField(blank=True, max_length=255, default='')
    # Sector
    sector = models.CharField(blank=True, max_length=455, default='')
    # Calle/Numero
    calle_numero = models.CharField(blank=True, max_length=255, default='')
    # municipio
    municipio = models.CharField(blank=True, max_length=255, default='')
    # Cuidad 
    ciudad = models.CharField(blank=True, max_length=250, default='Santo Domingo')
    # provincia
    provincia = models.CharField(blank=True, max_length=255, default='SANTO DOMINGO DE GUZMAN')
    # Pais
    pais = models.CharField(blank=True, max_length=255, default='REPUBLICA DOMINICANA')
    # dir_referencia
    dir_referencia = models.CharField(blank=True, max_length=255, default='')
    # Numero de telefono de la empresa
    phone = models.CharField(blank=True, max_length=18, default='')
    
    # Datos donde labura
    # Empresa donde trabaja  
    empresa_trabaja = models.CharField(blank=True, max_length=255, default='')
    # Cargo
    cargo = models.CharField( max_length=255, default='')
    # Direccion 
    direccion_trabajo = models.CharField(blank=True, max_length=255, default='')
    # Sector 
    sector = models.CharField(blank=True, max_length=244, default='')
    # Calle
    calle_numero_trabajo = models.CharField(blank=True, max_length=255, default='')
    # Municipio 
    municipio_trabaja = models.CharField(blank=True, max_length=255, default='')
    # Ciudad 
    ciudad_trabaja = models.CharField(blank=True, max_length=255, default='')
    # provins
    provincia_trabajo = models.CharField(blank=True, max_length=255, default='SANTO DOMINGO DE GUZMAN')
    # pais
    pais_trabajo = models.CharField(blank=True, max_length=244, default='REPUBLICA DOMINICANA')
    # dir_referencia
    dir_referencia_trabajo = models.CharField(blank=True, max_length=244, default='')
    #Salario de M
    salario_m = models.CharField( max_length=233, default='')
    # Moneda 
    moneda = models.CharField(blank=True, max_length=3, default='RD$')  
    # Datos de la cuantas 
    # Realcion tipo uno
    relacion_tipo = models.CharField(blank=True, max_length=233, default='1')
    # Fecha de Apertura
    fecha_apertura = models.CharField(blank=True, max_length=233, default='')
    # Fecha de Vencimiento
    fecha_vencimiento = models.CharField(blank=True, max_length=233, default='')
    # Fecha del ultimo pago
    fecha_ultimo_pago = models.CharField(blank=True, max_length=233, default='')
    # Numero de cuenta 
    numeoro_cuenta = models.CharField(blank=True, max_length=233, default='')
    # Estatus 
    estatus = models.CharField(blank=True, max_length=233, default='')
    # Tipo de prestamo
    tipo_prestamo = models.CharField(blank=True, max_length=233, default='N')
    # Moneda 
    moneda_prestamo = models.CharField(blank=True, max_length=233, default='RD$')
    # Credito Aprovado 
    credito_aprovado = models.CharField(blank=True, max_length=233, default='')
    #Balance al Corte
    balance_corte = models.CharField(blank=True, max_length=233, default='')
    #Monto Adeudado
    monto_adeudado = models.CharField(blank=True, max_length=233, default='')
    # Pago mandatotio o cuota
    pago_mandatorio_cuota = models.CharField(blank=True, max_length=233, default='')
    # Monto Ultimo Pago
    monto_ultimo_pago = models.CharField(blank=True, max_length=233, default='') 
    # Total de Atraso
    total_atraso = models.CharField(blank=True, max_length=233, default='')
    # Tasa de interes
    tasa_interes = models.CharField(blank=True, max_length=233, default='0.15')
    # Forma de pago 
    forma_pago = models.CharField(blank=True, max_length=233, default='Mensual')
    # Cantidad de Cuota
    cantidad_cuota = models.CharField(blank=True, max_length=233, default='6')
    atraso1_30 = models.CharField(blank=True, max_length=233, default='')
    atraso31_60 = models.CharField(blank=True, max_length=233, default='')
    atraso61_90 = models.CharField(blank=True, max_length=233, default='')
    atraso91_120 = models.CharField(blank=True, max_length=233, default='')
    atraso121_150 = models.CharField(blank=True, max_length=233, default='')
    atraso151_180 = models.CharField(blank=True, max_length=233, default='')
    atraso181_o_mas = models.CharField(blank=True, max_length=233, default='')

    day_created = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.name}, {self.last_name}, {self.company}'


class Category(models.Model):
        letter = models.CharField(max_length=1, default='A')
        def __str__(self):
            return f' Categoria ({self.letter})'

class Credit(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE,  blank=True, null=True, related_name="category_credit")
    company= models.ForeignKey('Company', on_delete=models.CASCADE,  blank=True, null=True, related_name="company_credit")
    customer = models.ForeignKey(Customer, null=True, blank=True, 
                    on_delete=models.CASCADE, related_name="credit")

FyCas/Shop/models.py
from django.db import models
from Customer.models import Company
# Create your models here.


from django.db import models

class Sale(models.Model):
      company= models.ForeignKey(Company, on_delete=models.CASCADE,  blank=True, null=True, related_name="sale_company")
      name = models.CharField(max_length=255, blank=True, null=True, default='Venta#')  # Nombre de la venta (puede ser el nombre del cliente o un código)
      total = models.DecimalField(max_digits=10, decimal_places=2)  # Total de la venta
      discount = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # Descuento aplicado (si hay)

      def __str__(self):
            return f"Venta: {self.name}, Total: RD$ {self.total}"



class Categori(models.Model):
      company= models.ForeignKey(Company, on_delete=models.CASCADE,  blank=True, null=True, related_name="categori_company")
      name = models.CharField(max_length=255, blank=True, null=True, default='Categoria 1') 
      img = models.ImageField(upload_to='media/categori/', blank=True, null=True) 
      
      def __str__(self):
            return f"Categoria: {self.name}"



class Item(models.Model):
      company= models.ForeignKey(Company, on_delete=models.CASCADE,  blank=True, null=True, related_name="item_company")
      name = models.CharField(max_length=255, blank=True, null=True, default='Articulo')  # Nombre del artículo
      price = models.DecimalField(max_digits=10, decimal_places=2,)  # Precio del artículo
      img = models.ImageField(upload_to='media/item/', blank=True, null=True)  # Imagen del artículo
      discount = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # Descuento aplicado al artículo
      stock = models.IntegerField(default=0)  # Stock disponible
      unit_of_measurement = models.CharField(max_length=50)  # Unidad de medida (ej. pieza, kg, etc.)

      def __str__(self):
            return f"Item: {self.name}, Precio: RD$ {self.price}, Stock: {self.stock}"

FyCas/Customer/templates/customer/archivos.html
{% include "base/base.html" %}
{% block content %}
{% load static %}
{% load humanize %}
<style>––
      table {
            width: 100%;
            border-collapse: collapse;
      }

      th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
      }

      th {
            background-color: #f2f2f2;
      }

      tr:hover {
            background-color: #f5f5f5;
      }
</style>

<table>
      <thead>
            <tr>
                  <th>Name</th>
                  <th>Age</th>
                  <th>Email</th>
            </tr>
      </thead>
      <tbody>
            <tr>
                  <td>John Doe</td>
                  <td>25</td>
                  <td>john@example.com</td>
            </tr>
            <tr>
                  <td>Jane Smith</td>
                  <td>30</td>
                  <td>jane@example.com</td>
            </tr>
            <tr>
                  <td>Mike Johnson</td>
                  <td>35</td>
                  <td>mike@example.com</td>
            </tr>
      </tbody>
</table>
{% endblock  %}

FyCas/Customer/templates/customer/create-credit.html
{% include "base/base.html" %}
{% block content %}
{% load static %}
<div class="p-3 d-flex  ">
      <div class="w-50 d-flex flex-wrap align-content-center  flex-wrap">
            <h3 class="p-0 m-0">
                  Crear Solicitud de Credito 
            </h3>
            <p class="text-black-50 w-100">
                  Esta solicitud proporciona información sobre el creiditario            
            </p>
      </div>
      <div class="d-flex justify-content-end w-50">
            <img src="{% static "icons/fycas.jpg" %}" weight="300" alt="" srcset="">
      </div>
</div>
<section class="p-3 section m-4">
      <div class="w-100">
            <h6 class="p-0  mt-1">
                  Datos Personales
            </h6>
            <p>
                  Revisar minuciosamente antes de enviar el formulario, reduce la posibilidad de errores
            </p>
      </div>
      <form action="" method="post">
            {% csrf_token %}

      <div class="d-flex  ">
            <!-- Customer Name for Input Value -->
            <input id="customer-name-complet" class="d-none" value="{{c.name}} {{c.last_name}}" type="text">
            <input id="customer-name" class="d-none" value="{{c.name}} {{c.last_name}}" type="text">
            <input id="customer-dni" class="d-none" value="{{c.dni}}" type="text">

            <div class="form-floating mb-3  w-50" >
                  {{form.customer}} 
                  <label for="">
                        Cliente 
                  </label>
            </div>
            <div class="form-floating mb-3 w-50" >
                  {{form.name}}
                  <label for="">
                        Nombre
                  </label>
            </div>
            <div class="form-floating mb-3 w-50" >
                  {{form.dni}}
                  <label for="">
                        No. Cedula
                  </label>
            </div>

      </div>
      <div class="w-100">
            <h6 class="p-0  mt-2">
                  Detalles del préstamo
            </h6>
            <p>
                  Monto del préstamo, tasa de interés, plazo del préstamo, tipo de préstamo.
            </p>
      </div>
      <div class="d-flex">
            <div class="form-floating mb-3 w-50" >
                  {{form.amount}}
                  <label for="id_work_information">Monto
                  </label>
            </div>
            <div class="form-floating mb-3 w-50" >
                  {{form.price_feed}}
                  <label for="id_work_information">Cuota A Pagar
                  </label>
            </div>

            <div class="form-floating mb-3 w-50" >
                  {{form.no_account}} 
                  <label for="">
                        No.  Cuenta
                  </label>
            </div>
      </div>
      <div class="w-100 d-flex">
            <div class="form-floating mb-3 " >
                  {{form.day_pay}}
                  <label for="id_work_information">Dia de Pago
                  </label>
            </div>
            <div class=" mb-3 ms-3  d-flex align-content-center " >
                  {{form.mode_pay}}
                  <label for="id_mode_pay" class="d-flex h-100 flex-wrap ms-1 align-content-center justify-content-center"> Aplicar dos pagos (15) - (30)
                  </label>
            </div>
      </div>

      <div class="form- mb-3 w-100 " >
          <div >
            <h6 class="ms-1"> Ganancias: <span class="text-black" id="resultado-div"></span>.00</h6>
          </div>
          <div class="">
            <h6 class="ms-1"> Cuota Mensual: <span class="text-black" id="valor-div"></span></h6>
          </div>
          <div class="form-floating mb-3 " >
            {{form.amount_feed}}
            <label for="id_amount_feed">Cuota Mensual
            </label>
         </div>
      </div>
      <div class="d-">

      </div>
      <div class="d-flex w-100 pt-4 justify-content-end">
            <a href="{% url "customer:list-customer" %}" class="btn-cancel">
                  Cancelar
            </a>
            <button class="btn-save">
                  Enviar
            </button>
      </div>
</form>
</section>
<script>
     let customer =  document.getElementById("id_customer")
     customer.classList.add("text-uppercase", "text-black-50")
     customer.value =  document.getElementById("customer-name-complet").value 
     customer.disabled = true       

     document.getElementById("id_name").value =  document.getElementById("customer-name").value 
     document.getElementById("id_dni").value =  document.getElementById("customer-dni").value 


      let price_feed = document.getElementById("id_price_feed")
      price_feed.addEventListener("input", () => {

                  CalcularDivisas()

      })
      let amoun = document.getElementById("id_amount")
      amoun.addEventListener("input", () => {
            CalcularDivisas()
      })

      window.onload = CalcularDivisas()

      function CalcularDivisas() {
            let p = parseFloat(document.getElementById("id_price_feed").value);
            let amounts = parseFloat(document.getElementById("id_amount").value);
            const int = p * 0.1;
            // Formatear "intereses" con comas
            let cuotas = int * amounts
            let total = cuotas + amounts
            let tt = total / p 
            let total_c = Math.round(cuotas);
            document.querySelector("#resultado-div").textContent ='RD$' + total.toLocaleString() ;
            document.querySelector("#valor-div").textContent = 'RD$' + tt.toLocaleString()
}



</script>

{%  endblock%}                                                                                                                        

FyCas/Customer/templates/customer/create-customer-debeit.html
{% include "base/base.html" %}
{% block content %}
      <section class='container-fluid' style='max-width: 30rem;'> 
            <div>
                  <h5>
                        Creando Deudor
                  </h5>
            </div>
            <form action="" method="post">
                  {% csrf_token %}
                  <div class='form-floating mb-2'>
                        {{form.name}}
                        <label for="id_name">Nombre</label>
                  </div>
                  <div class='form-floating mb-2'>
                        {{form.dni}}
                        <label for="id_dni">Cedula</label>
                  </div>
                  <div class='form-floating mb-2'>
                        {{form.number}}
                        <label for="id_number">Numero</label>
                  </div>
                  <div class='d-flex w-100 justify-content-end'>
                        <button class='btn btn-primary border-0' style='border-radius: 1.5rem;'>
                              Crear deudor
                        </button>
                  </div>
            </form>
      </section>

      <script>
            function DNI(value) {
                  // Elimina todos los caracteres no numéricos
                  var number_dni = value.replace(/\D/g, '');
                  // Agrega guiones después de los primeros 3 dígitos y los siguientes 7 dígitos
                  var dni_ = number_dni.replace(/(\d{3})(\d{7})(\d{1})/, '$1-$2-$3');
                  return dni_;
                }
                // Agrega un evento al campo de entrada
                  document.getElementById('id_dni').addEventListener('input', function(e) {
                  let dni = document.getElementById('id_dni')
                  dni.value = dni.value.slice(0, 13);
                  e.target.value = DNI(e.target.value);
                });

                function NumbersFomat(value) {
                  // Elimina todos los caracteres no numéricos
                  var number = value.replace(/\D/g, '');
                  // Agrega guiones después de los primeros 3 dígitos y los siguientes 7 dígitos
                  var N = number.replace(/(\d{3})(\d{3})(\d{1})/, '$1-$2-$3');
                  return N;
                }

                document.getElementById('id_number').addEventListener('input', function(e) {
                  let n = document.getElementById('id_number')
                  n.value = n.value.substring(0,12);
                  e.target.value = NumbersFomat(e.target.value);
        });
      
      </script>

{% endblock  %}

FyCas/Customer/templates/customer/prestamos.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
{% load humanize %}

<style>
      .btn-configuraciones
      {
            background-color: #eeeeee !important;
      }
</style>
{% include "components/background-animated.html" %}
<section class="w-100 blur h-100 position-absolute top-0 start-0 d-flex   justify-content-center align-content-center flex-wrap"
      style="z-index: 0;">

      <div class="justify-content-center text-center p-2">
            <h4>
                  Ups!  Aun esta en desarrollo
            </h4> 
            <p class="text-black-50" style="font-size: 14px;">
                  Si quieres activar ver esta caracteristica antes de su lanzamiento, ve a configuraciones y activa la <strong>"True Dev"</strong>, esto para ir provando las nuevas caracteristicas
            </p>
      </div>

</section>


{% endblock %}