FyCas/Customer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, views_ajax

app_name = "customer"
urlpatterns = [
      path("", views.Dashboard.as_view(), name='dashboard'),
      path('add-customer/<int:pk>', views.AddCustomer.as_view(), name='add-customer'),
      path('detail-customer/<int:pk>', views.DetailCustomer.as_view(), name='detail-customer'),
      path('update-customer/<int:pk>', views.UpdateCustomer.as_view(), name='update-customer'),
      
      path('delete-customer/<int:pk>', views.DeleteCustomer.as_view(), name='delete-customer'),

      path('list-customer', views.ListCustomer.as_view(), name='list-customer'),
      path('card-customer/<int:pk>/<int:credit_id>', views.CardCustomer.as_view(), name='card-customer'),
      path('notary-customer/<int:pk>/<int:notary_id>', views.NotaryCustomer.as_view(), name='notary-customer'),
      
      path('create-credit/<int:pk>', views.CreateCredit.as_view(), name='create-credit'),
      path('update-credit/<int:pk>', views.UpdateCredit.as_view(), name='update-credit'),
      path('list-credit/<int:pk>', views.ListCredit.as_view(), name='list-credit'),

      path('create-credit-new/<int:pk>', views.CreateCreditNew.as_view(), name='create-credit-new'),

      path('calendario/', views.Calendario.as_view(), name='calendario'),

      path('configuraciones/', views.Configuraciones.as_view(), name='configuraciones'),

      path("detail-credit/customer/<int:pk>", views.DetailCreditCustomer.as_view(), name="detail-credit-cutomer"),

      path("no-approved/customer", views.NoApproved.as_view(), name='no-approved'),
      path("approved/customer/<int:pk>", views.Approved.as_view(), name='approved'),
      
      path("create/customer-debit", views.CreateCustomerDebit.as_view(), name='create-customer-debit'),
      path("mensaje/customer-debit", views.MensajeCustomerDebit.as_view(), name='mensaje-customer-debit'),

      path("select/customer", views.ListCustomerSelect.as_view(), name='select-customer'),
      
      path("customer-profile", views.CustomerProfile.as_view(), name='customer-profile'),
      path('mensajeria', views.Mensensajeria.as_view(), name='mensajeria'),

      path("prestamos", views.Prestamos.as_view(), name='prestamos'),
      
      path('ubicaciones', views.Ubicaciones.as_view(), name='ubicaciones'),
      path('agregar/<int:pk>', views.Agregar.as_view(), name='agregar'),

      path('listado-credit-redirect/<int:pk>', views.ListadoCredit_rederict.as_view(), name='listado-credit-redirect'),

      path('empresa', views.Empresa.as_view(), name='empresa'),
      path('calculadora', views.Calculadora.as_view(), name='calculadora'),

      # New Version
      path('crear-credito/<int:pk>', views.CrearCredito.as_view(), name='crear-credito'),
      path('list-all-credits', views.ListAllCredits.as_view(), name='list-all-credits'),

      path('search-company', views.SearchCompany.as_view(), name='search-company'),

      path('select-form', views.SelecForm.as_view(), name='select-form'),


      # Views Ajax``
      path('aplicar-pago', views_ajax.AplicarPago, name='aplicar-pago'),
      path("searching/customer", views_ajax.SearchCustomer, name="searching-customer"),
      path("verify/customer/", views_ajax.CustomerVerify, name="verify-true-customer"),
      path("verify-no/customer/", views_ajax.CustomerNoVerify, name="verify-false-customer"),
      path('calcular-mora', views_ajax.CalcularMora, name='calcular-mora'),
      path("turn-debit/customer/", views_ajax.TurnDebeit, name="turn-debit-customer"),
      path("turn-debit-follow/customer/", views_ajax.TurnDebeitFollow, name="turn-debit-customer-follow"),
      path("turn-debit-active/customer/", views_ajax.TurnDebeitActive, name="turn-debit-customer-active"),
      path("msg/customer/debit", views_ajax.MensajeCustomerDebit, name="msg-debit-customer"),
      path("create-credit-ajax/customer/", views_ajax.CreateCreditAjax, name="create-credit-ajax"),
      path("disable-customer/", views_ajax.DisableCustomer, name="disable-customer-ajax"),
      path("delete-credit", views_ajax.DeleteCreditAjax, name="delete-credit"),
      path('upload-image-url', views_ajax.UploadImageURL, name='upload-image-url'),
      

      path('chatgpt', views_ajax.ChatGPT, name='chatgpt'),

      path('aplicar-pago-cuota', views_ajax.AplicarPagoCuota, name='aplicar-pago-cuota'),

      path('abonar-capital', views_ajax.AbonarCapital, name='abonar-capital')
      
]

FyCas/FyCas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Customer.urls')),
    path('', include('Maps.urls')),
    path('', include('MensApp.urls')),
     path('', include('Shop.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FyCas/Maps/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "maps"
urlpatterns = [
      path('maps/customer', views.Maps.as_view(), name='maps-customer'),
      path('data-credito/', views.DataCredit.as_view(), name='data-credi')
      
]

FyCas/Customer/models.py
from django.db import models
from django.utils import timezone
from PIL import Image
import os
from django.core.files.base import ContentFile
from io import BytesIO

from django.contrib.auth.models import User




# Create your models here.

class Customer(models.Model):
    company= models.ForeignKey('Company', on_delete=models.CASCADE,  blank=True, null=True, related_name="company_customer")
    # Para el tema de las solicitudes, cuando el user ingresa por primera vez el estado permanece false durante los proximos 7 dias, sera descartado y eliminado de la base de datos ya que su aprobacion no fue verificada por lo tanto no cambio a " True " pero se guardada su DNI en una base de datos adicional mas adelante p
    not_aprobado = models.BooleanField(default=False,  blank=True)
    # Si 
    customer_verify = models.BooleanField(default=False,  blank=True)
   
    debit = models.BooleanField(default=False,  blank=True)
    
    debit_visit = models.BooleanField(default=False,  blank=True)
    debit_follow = models.BooleanField(default=False,  blank=True)

    
    # Datos Opcionales
    vehiculo = models.BooleanField(default=False,  blank=True)
    casa = models.BooleanField(default=False,  blank=True)
    tierra = models.BooleanField(default=False,  blank=True)
    
    hijos = models.BooleanField(default=False,  blank=True)
    saldar_deudas = models.BooleanField(default=False,  blank=True)

    
    # Preguntas 
    familiar_en_fycas = models.BooleanField(default=False, blank=True)
    fue_recomendado = models.BooleanField(default=False,  blank=True)
    
    monto_requerido = models.CharField(max_length=255, default='',  blank=True)
    fines = models.CharField(max_length=255, default='',  blank=True)
    

    is_active = models.BooleanField(default=True)
    name = models.CharField( max_length=255, )#Nombre
    last_name = models.CharField( max_length=255)#Apellido
    number = models.CharField( max_length=20, )#Numero local o Movile
    address = models.CharField( max_length=255, blank=True)#Direccion de donde recide
    email = models.EmailField(null=True, blank=True)#Correo electronico
    amount_purpose = models.TextField(blank=True, max_length=355)#Proposito por el que se solicita el prestamo
    work_information = models.TextField(blank=True, max_length=300)#Informacion donde trabaja
    references_peopple = models.TextField(blank=True, max_length=500)#Personas referentes
    dni = models.CharField( max_length=100) #Numero de Identidad
    amount = models.IntegerField(null=True)#Monto 
    no_account = models.IntegerField(default=0) #Numero de Cuentaloooo
    
    img1 = models.ImageField(upload_to="media/",  blank=True, null=True, default=None)
      #Foto de Cedula delantera
    img2 = models.ImageField(upload_to="media/", blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        # Save the original instance first to ensure img1 is available
        super(Customer, self).save(*args, **kwargs)

        if self.img1:
            try:
                img2 = self.img1.path
                # Open the original image
                img1_path = self.img1.path
                img1 = Image.open(img1_path)

                # Resize img1 to 250p resolution
                img1.thumbnail((50, 50))
                img1_io = BytesIO()
                img1.save(img1_io, format=img1.format, quality=50)  # Reduce quality to reduce file size

                self.img1.save(os.path.basename(self.img1.name), ContentFile(img1_io.getvalue()), save=False)
            except FileNotFoundError:
                pass

        super(Customer, self).save(*args, **kwargs)


    #Foto de Cedula tracera
    name_r1 = models.CharField( max_length=255,  )#Nombre
    name_r2 = models.CharField( max_length=255,  )#Nombre
    number_r1 = models.CharField(default="",  max_length=30)#Numero local o Movile
    number_r2 = models.CharField(default="",  max_length=30  )#Numero local o Movile
    
    # CaptureLocation
    lat = models.CharField(blank=True, max_length=100000000050005, default='')
    lon = models.CharField(blank=True, max_length=100000000000000055, default='')
    
    # Tipo de Entrada
    type_input = models.CharField(blank=True, max_length=2, default='P')
    #Sexo
    sexo = models.CharField(blank=True, max_length=2, default='M')
    # Estado Civil 
    estado_civil = models.CharField(blank=True, max_length=2, default='')
    # Ocupacion 
    ocupacion = models.CharField(blank=True, max_length=25, default='Estudiante')
    # Codigo de cliente
    code_customer = models.CharField(blank=True, max_length=122000, default='')
    # Date 
    nacimiento = models.CharField(blank=True, max_length=40, default='10/11/2001')
    # Nacionalidad 
    nacionalidad = models.CharField(blank=True, max_length=25, default='DOMINICANA')
    # Direccion
    direccion = models.CharField(blank=True, max_length=255, default='')
    # Sector
    sector = models.CharField(blank=True, max_length=455, default='')
    # Calle/Numero
    calle_numero = models.CharField(blank=True, max_length=255, default='')
    # municipio
    municipio = models.CharField(blank=True, max_length=255, default='')
    # Cuidad 
    ciudad = models.CharField(blank=True, max_length=250, default='Santo Domingo')
    # provincia
    provincia = models.CharField(blank=True, max_length=255, default='SANTO DOMINGO DE GUZMAN')
    # Pais
    pais = models.CharField(blank=True, max_length=255, default='REPUBLICA DOMINICANA')
    # dir_referencia
    dir_referencia = models.CharField(blank=True, max_length=255, default='')
    # Numero de telefono de la empresa
    phone = models.CharField(blank=True, max_length=18, default='')
    
    # Datos donde labura
    # Empresa donde trabaja  
    empresa_trabaja = models.CharField(blank=True, max_length=255, default='')
    # Cargo
    cargo = models.CharField( max_length=255, default='')
    # Direccion 
    direccion_trabajo = models.CharField(blank=True, max_length=255, default='')
    # Sector 
    sector = models.CharField(blank=True, max_length=244, default='')
    # Calle
    calle_numero_trabajo = models.CharField(blank=True, max_length=255, default='')
    # Municipio 
    municipio_trabaja = models.CharField(blank=True, max_length=255, default='')
    # Ciudad 
    ciudad_trabaja = models.CharField(blank=True, max_length=255, default='')
    # provins
    provincia_trabajo = models.CharField(blank=True, max_length=255, default='SANTO DOMINGO DE GUZMAN')
    # pais
    pais_trabajo = models.CharField(blank=True, max_length=244, default='REPUBLICA DOMINICANA')
    # dir_referencia
    dir_referencia_trabajo = models.CharField(blank=True, max_length=244, default='')
    #Salario de M
    salario_m = models.CharField( max_length=233, default='')
    # Moneda 
    moneda = models.CharField(blank=True, max_length=3, default='RD$')  
    # Datos de la cuantas 
    # Realcion tipo uno
    relacion_tipo = models.CharField(blank=True, max_length=233, default='1')
    # Fecha de Apertura
    fecha_apertura = models.CharField(blank=True, max_length=233, default='')
    # Fecha de Vencimiento
    fecha_vencimiento = models.CharField(blank=True, max_length=233, default='')
    # Fecha del ultimo pago
    fecha_ultimo_pago = models.CharField(blank=True, max_length=233, default='')
    # Numero de cuenta 
    numeoro_cuenta = models.CharField(blank=True, max_length=233, default='')
    # Estatus 
    estatus = models.CharField(blank=True, max_length=233, default='')
    # Tipo de prestamo
    tipo_prestamo = models.CharField(blank=True, max_length=233, default='N')
    # Moneda 
    moneda_prestamo = models.CharField(blank=True, max_length=233, default='RD$')
    # Credito Aprovado 
    credito_aprovado = models.CharField(blank=True, max_length=233, default='')
    #Balance al Corte
    balance_corte = models.CharField(blank=True, max_length=233, default='')
    #Monto Adeudado
    monto_adeudado = models.CharField(blank=True, max_length=233, default='')
    # Pago mandatotio o cuota
    pago_mandatorio_cuota = models.CharField(blank=True, max_length=233, default='')
    # Monto Ultimo Pago
    monto_ultimo_pago = models.CharField(blank=True, max_length=233, default='') 
    # Total de Atraso
    total_atraso = models.CharField(blank=True, max_length=233, default='')
    # Tasa de interes
    tasa_interes = models.CharField(blank=True, max_length=233, default='0.15')
    # Forma de pago 
    forma_pago = models.CharField(blank=True, max_length=233, default='Mensual')
    # Cantidad de Cuota
    cantidad_cuota = models.CharField(blank=True, max_length=233, default='6')
    atraso1_30 = models.CharField(blank=True, max_length=233, default='')
    atraso31_60 = models.CharField(blank=True, max_length=233, default='')
    atraso61_90 = models.CharField(blank=True, max_length=233, default='')
    atraso91_120 = models.CharField(blank=True, max_length=233, default='')
    atraso121_150 = models.CharField(blank=True, max_length=233, default='')
    atraso151_180 = models.CharField(blank=True, max_length=233, default='')
    atraso181_o_mas = models.CharField(blank=True, max_length=233, default='')

    day_created = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.name}, {self.last_name}, {self.company}'


class Category(models.Model):
        letter = models.CharField(max_length=1, default='A')
        def __str__(self):
            return f' Categoria ({self.letter})'

class Credit(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE,  blank=True, null=True, related_name="category_credit")
    company= models.ForeignKey('Company', on_delete=models.CASCADE,  blank=True, null=True, related_name="company_credit")
    customer = models.ForeignKey(Customer, null=True, blank=True, 
                    on_delete=models.CASCADE, related_name="credit")

FyCas/Customer/templates/components/info-laboral.html
{% load static %}

<section class="mt-5 w-100 sec-sl d-flex flex-wrap justify-content-center">
      <div class="w-100 d-flex img-glouds align-content-center m-1 " 
      style='background-color: #F6F6F6; max-width: 30rem; 
      border-radius: 35px;'>
      <div class="img-data d-flex flex-wrap align-content-center justify-content-center">
            <img src="{% static "icons/doc(44).png" %}"
                  width='134' height='124' alt="">
      </div>
      <div class='d-flex flex-wrap align-content-center'>
            <h6>
                  Informacion Laboral
            </h6>
            <p class="text-black-50 mt-4">
                  Lugar de Trabajo, Cargo o (Funcion), Ingresos Mensuales y Numero de Contacto de la Empresa.
            </p>
      </div>
</div>
<section class=" d-flex flex-wrap align-content-center w-100 " style="max-width: 30rem;">
      <div class="d-flex w-100 mt-4">
            <div class="form-floating mb-2 w-50 " >
                  {{form.empresa_trabaja}}
                  <label for="id_work_information">
                        Empresa donde  Trabaja</label>
            </div>
            <div class="form-floating mb-2 w-50 " >
                  {{form.cargo}}
                  <label for="id_work_information">Cargo o (Funcion)</label>
            </div>
      </div>
      <div class="d-flex w-100">
            <div class="form-floating mb-2  w-50 " >
                  {{form.salario_m}}
                  <label for="id_work_information">Ingresos Mensuales</label>
            </div>
            <div class="form-floating mb-2  w-50" >
                  {{form.phone}}
                  <label for="id_work_information"> Contacto de la Empresa</label>
            </div>
      </div>
      <div class="d-flex justify-content-end align-content-center mt-5 w-100 flex-wrap">    
            <label class="bg-transparent scroll-btn text-black " style="width: 100px;" onclick='scrollToLast()'>Atras</label>
            <label class="scroll-btn" onclick="scrollToNext()">Siguiente 
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                  <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
                      </svg>
            </label>
      </div>

</section>
</section>

<script>

function NumbersFomat(value) {
          // Elimina todos los caracteres no numéricos
          var number = value.replace(/\D/g, '');
          // Agrega guiones después de los primeros 3 dígitos y los siguientes 7 dígitos
          var N = number.replace(/(\d{3})(\d{3})(\d{1})/, '$1-$2-$3');
          return N;
        }

document.getElementById('id_phone').addEventListener('input', function(e) {
                  let n = document.getElementById('id_phone')
                  n.value = n.value.slice(0, 12);
                  e.target.value = NumbersFomat(e.target.value);
                  
        });

        document.getElementById('id_salario_m').addEventListener('input', function(e) {
                  let n = document.getElementById('id_salario_m')
                  n.value = n.value.slice(0, 29);
                  e.target.value = NumbersFomatSalari(e.target.value);
                  
        });
      
</script>


      


      

FyCas/Customer/templates/components/options.html
{% load static %}
<section class="mt-5 w-100 sec-sl d-flex flex-wrap justify-content-center">

<div class="w-100 d-flex img-glouds align-content-center m-1 " 
      style='background-color: #F6F6F6; max-width: 30rem; 
      border-radius: 35px;'>
      <div class="img-data d-flex flex-wrap align-content-center">
            <img src="{% static "icons/doc(42).png" %}"
                  width='134' height='124' alt="">
      </div>
      <div class='d-flex flex-wrap align-content-center'>
            <h6>
                  ¿Cuales de estas opciones aplican a ti?
            </h6>
            <p class="text-black-50 mt-4">
                  Seleccione todas las opciones que apliquen a ti
            </p>
      </div>
</div>
<section class=" d-flex flex-wrap align-content-center w-100 " style="max-width: 30rem;">
      <section class="w-100 d-flex flex-wrap text-black-50 justify-content-start" style="text-align: justify; width: 330px;">
  
            <div class="form-check w-100  mt-3  " >
                  <label class="ms-3" for="id_familiar_en_fycas"> ¿Tiene Familiar es cliente de Grupo Fycas?</label>
                  {{form.familiar_en_fycas}}
            </div>
            
            <div class="form-check w-100   " >
                  <label class="ms-3" for="id_vehiculo"> ¿Vehículo</strong> de su propiedad?</label>
                  {{form.vehiculo}}
            </div>
            <div class="form-check w-100    " >
                  <label class="ms-3" for="id_fue_recomendado"> ¿Fuiste recomendado por Alguien?</label>
                  {{form.fue_recomendado}}
            </div>
            <div class="form-check w-100    " >
                  <label class="ms-3" for="id_tierra">¿Posee Terreno de su propiedad?</label>
                  {{form.tierra}}
            </div>
      
            <div class="form-check w-100   " >
                  <label class="ms-3" for="id_saldar_deudas"> ¿Te gustaria saldar deudas?</label>
                  {{form.saldar_deudas}}
            </div>
      
            <div class="form-check w-100    " >
                  <label class="ms-3" for="id_hijos"> ¿Tienes hijos?</label>
                  {{form.hijos}}
            </div>
            
            <div class="form-check w-100   mb-4" >
                  <label class="ms-3" for="id_casa"> ¿Posee Casa  de su propiedad?</label>
                  {{form.casa}}
            </div>
      </section>



      <div class="d-flex justify-content-end align-content-center mt-5 w-100 flex-wrap">    
            <label class="bg-transparent scroll-btn text-black " style="width: 100px;" onclick='scrollToLast()'>Atras</label>
            <label class="scroll-btn" onclick="scrollToNext()">Siguiente 
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                  <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
                      </svg>
            </label>
      </div>

</section>


      

</section>

FyCas/Customer/templates/components/referens.html
{% load static %}
<section class="mt-5 w-100 sec-sl d-flex flex-wrap justify-content-center">

<div class="w-100 d-flex img-glouds align-content-center m-1 " 
style='background-color: #F6F6F6; max-width: 30rem; 
border-radius: 35px;'>
<div class="img-data d-flex flex-wrap align-content-center justify-content-center">
      <img src="{% static "icons/doc(43).png" %}"
            width='164' height='194' alt="">
</div>
<div class='d-flex flex-wrap align-content-center'>
      <h6>
          Referencias Personales
      </h6>
      <p class="text-black-50 mt-4">
         Proporcione dos referencias personales, comuniquelos antes de proporcionarlos.
      </p>
</div>
</div>
<section class=" d-flex flex-wrap align-content-center w-100 " style="max-width: 30rem;">
<div class="w-100 mt-4">
      <p class="text-black-50 m-0 ms-2">
            Debe proporcionar una referencia que recida con usted o trabaje en la misma ciudad.
      </p>
</div>
<div class="w-100 d-flex ">
      <div class="form-floating mb-2 w-50  " >
            {{form.name_r1}}
            <label for="id_work_information">Nombre 
            </label>
      </div>
      <div class="form-floating mb-2 w-50  " >
            {{form.number_r1}}
            <label for="id_work_information">Numero 
            </label>
      </div>
</div>

<div class="w-100">
      <p class="text-black-50 m-0 ms-2 mt-2">
            Debe colocar como segunda referencia a un familiar o amigo cercano.
      </p>
</div>
{{form.lat}} {{form.lon}}
<div class="w-100 d-flex ">
      <div class="form-floating m-0 mb-2 w-50  " >
            {{form.name_r2}}
            <label for="id_work_information">Nombre familiar o amigo 
            </label>
      </div>
      <div class="form-floating mb-2 w-50 " >
            {{form.number_r2}}
            <label for="id_number_r2">Numero familiar o amigo 
            </label>
      </div>
</div>



<div class="d-flex justify-content-end align-content-center mt-5  w-100 flex-wrap">    
      <label class="bg-transparent scroll-btn text-black " style="width: 100px;" onclick='scrollToLast()'>Atras</label>
      <label class="scroll-btn" onclick="scrollToNext()">Siguiente 
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z"/>
                </svg>
      </label>
</div>

</section>

</section>

      <script>
               function NumbersFomat(value) {
          // Elimina todos los caracteres no numéricos
          var number = value.replace(/\D/g, '');
          // Agrega guiones después de los primeros 3 dígitos y los siguientes 7 dígitos
          var N = number.replace(/(\d{3})(\d{3})(\d{1})/, '$1-$2-$3');
          return N;
        }

        document.getElementById('id_number_r1').addEventListener('input', function(e) {
                  let n = document.getElementById('id_number_r1')
                  n.value = n.value.slice(0, 12);
                  e.target.value = NumbersFomat(e.target.value);
        });
      
      document.getElementById('id_number_r2').addEventListener('input', function(e) {
                  let n = document.getElementById('id_number_r2')
                  n.value = n.value.slice(0, 12);
                  e.target.value = NumbersFomat(e.target.value);
                  
        });
      
      </script>


<!--       

<div>
      <img src="{% static "icons/doc(43).png" %}" class="" width='284'  alt="">
</div>
<strong class="p-0 m-0   w-100 ms-2">
      Referencias Personales
</strong>
<section class="w-100 d-flex flex-wrap  ">
      <p class="text-black-50 m-0 ms-2">
            Asegúrese de que sus referencias estén al tanto de que las proporcionará como referencia.
      </p>
      <div class="w-100">
    
         
      </div>
</section> -->

FyCas/Customer/templates/components/select-form.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
{% load humanize %}

<style>

.btn-agregar
{
      background-color: var(--bg-enfasis) !important;
      color: white !important;
      width: max-content !important;
      
}
.btn-agregar img 
{
      display: none;
}
.welcome-screen .card 
{
      cursor: pointer; width: 25rem; margin: 1rem;
}
.form-control input
{
      width: 20rem;
      padding: 0.5rem;
      border-radius: 0.5rem;
}
.form-control
{
      margin: 1rem;  width: max-content;

}
</style>

<div class="welcome-screen">

      <div class="d-flex justify-content-center flex-wrap align-content-center  vh-100 ">

              <div class="card rounded-5">
                <div class="card-body">
                  <h5 class="card-title p-0 m-0 mb-3"> Agregar cliente facil </h5>
                  <p class="card-text text-black-50" style="font-size: 12px;">
                        Nombre, apellido, cedula, telefono o correo
                  </p>
                </div>
              </div>

              <a href="{% url "customer:agregar" company.id %}" style="width: max-content;">
              <div class="card rounded-5">
                <div class="card-body">
                  <h5 class="card-title p-0 m-0 mb-3"> Agregar cliente extenso</h5>
                  <p class="card-text text-black-50" style="font-size: 12px;">
                        Nombre, apellido, cedula, foto de cedula, telefono, correo, direccion, etc
                  </p>
                </div>
              </div>
          </div>
      </a>



      <section class="d-flex  flex-wrap d-none">
            <div class="form-control">
                    <label for="id_name">Nombre</label>
                    {{ form.name }}
            </div>
            <div class="form-control">
                    <label for="id_last_name">Apellido</label>
                    {{ form.last_name }}
            </div>
            <div class="form-control">
                    <label for="id_phone">Teléfono</label>
                    {{ form.phone }}
            </div>
            <div class="form-control">
                    <label for="id_dni">Cedula</label>
                    {{ form.dni }}
            </div>
      </section>



</div>

<script>

document.querySelectorAll('.welcome-screen .card').forEach(card => {
      card.addEventListener('mouseover', () => {
            card.classList.add('shadow');
      });
      card.addEventListener('mouseout', () => {
            card.classList.remove('shadow');
      });
});


</script>

{% endblock %}